/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter.interfaz;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.GestionTwitter;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import twitter4j.Twitter;

/**
 *
 * @author zapia
 */
public class PantallaInformes extends javax.swing.JDialog {

    private JRDataSource dataSource;
    private Map parametros;
    private JasperPrint print;
    private Twitter twitterConnection;

    /**
     * Creates new form PantallaInformes
     */
    public PantallaInformes(java.awt.Frame parent, boolean modal, Twitter twitter) {
        super(parent, modal);
        this.twitterConnection = twitter;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jBFollow = new javax.swing.JButton();
        jBFollowers = new javax.swing.JButton();
        jBTweetsUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Tweet publicados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBCerrar.setText("Cerrar");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });

        jBFollow.setText("Follows");
        jBFollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFollowActionPerformed(evt);
            }
        });

        jBFollowers.setText("Followers");
        jBFollowers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFollowersActionPerformed(evt);
            }
        });

        jBTweetsUser.setText("Tweets de un usuario");
        jBTweetsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTweetsUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCerrar)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFollow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFollowers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTweetsUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jBFollow)
                .addGap(18, 18, 18)
                .addComponent(jBFollowers)
                .addGap(32, 32, 32)
                .addComponent(jBTweetsUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jBCerrar)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            dataSource = new JRBeanCollectionDataSource(GestionTwitter.listaTweetsPropiosInforme(twitterConnection));
            parametros = new HashMap();
            print = JasperFillManager.fillReport("reports/jasper/informeTwitter.jasper", parametros, dataSource);
            JasperExportManager.exportReportToPdfFile(print, "reports/pdf/informeTwitter" + ".pdf");
        } catch (JRException ex) {
            Logger.getLogger(PantallaInformes.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Informe guardado en \"reports/pdf\" con éxito");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBFollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFollowActionPerformed
        try {
            dataSource = new JRBeanCollectionDataSource(GestionTwitter.listaSeguidosInforme(twitterConnection));
            parametros = new HashMap();
            print = JasperFillManager.fillReport("reports/jasper/informeFollows.jasper", parametros, dataSource);
            JasperExportManager.exportReportToPdfFile(print, "reports/pdf/follows" + ".pdf");
        } catch (JRException ex) {
            Logger.getLogger(PantallaInformes.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Informe guardado en \"reports/pdf\" con éxito");
    }//GEN-LAST:event_jBFollowActionPerformed

    private void jBFollowersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFollowersActionPerformed
        try {
            dataSource = new JRBeanCollectionDataSource(GestionTwitter.listaSeguidoresInforme(twitterConnection));
            parametros = new HashMap();
            print = JasperFillManager.fillReport("reports/jasper/followers.jasper", parametros, dataSource);
            JasperExportManager.exportReportToPdfFile(print, "reports/pdf/followers" + ".pdf");
        } catch (JRException ex) {
            Logger.getLogger(PantallaInformes.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Informe guardado en \"reports/pdf\" con éxito");
    }//GEN-LAST:event_jBFollowersActionPerformed

    private void jBTweetsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTweetsUserActionPerformed
        String usuario = JOptionPane.showInputDialog("Introduzca un usuario");
        
        if (usuario.equals("") || usuario == null) {
            JOptionPane.showMessageDialog(this, "Tiene que escoger un usuario");
        } else {
            try {
                dataSource = new JRBeanCollectionDataSource(GestionTwitter.listaTweetsUsuarioInforme(twitterConnection, usuario));
                parametros = new HashMap();
                print = JasperFillManager.fillReport("reports/jasper/tweetsUsuario.jasper", parametros, dataSource);
                JasperExportManager.exportReportToPdfFile(print, "reports/pdf/informeTweetsUsuario" + ".pdf");
            } catch (JRException ex) {
                Logger.getLogger(PantallaInformes.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Informe guardado en \"reports/pdf\" con éxito");
        }
    }//GEN-LAST:event_jBTweetsUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBFollow;
    private javax.swing.JButton jBFollowers;
    private javax.swing.JButton jBTweetsUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
