/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter.interfaz;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import logica.GestionTwitter;
import twitter4j.Status;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;

/**
 *
 * @author migue
 */
public class PantallaPrincipal extends javax.swing.JDialog {

    Twitter twitterConnection;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal(java.awt.Frame parent, boolean modal, Twitter twitterConnection) {
        super(parent, modal);
        this.twitterConnection = twitterConnection;
        initComponents();
        setLocationRelativeTo(parent);
        try {
            File fichero = new File("help/help_set.hs");
            URL hsURL = fichero.toURI().toURL();
            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();
            // Pone ayuda a item de menu al pulsarlo.
            hb.enableHelpKey(this.getContentPane(), "ventana_secundaria", helpset);
        } catch (MalformedURLException | HelpSetException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jLabelUsuario.setText("@" + twitterConnection.getScreenName());
            jLabelNickName.setText(twitterConnection.getUserTimeline().get(0).getUser().getName());
            jButtonlCantidadSiguiendo.setText(String.valueOf(GestionTwitter.seguidos(twitterConnection).size()));
            jButtonlCantidadSeguidores.setText(String.valueOf(GestionTwitter.seguidores(twitterConnection).size()));
            jButtonTweets.setText(String.valueOf(twitterConnection.getUserTimeline().size()));
            jListTTEsp.setModel(GestionTwitter.trendindTopicsEsp(twitterConnection));
            jListTTGlobal.setModel(GestionTwitter.trendindTopicsGlobales(twitterConnection));
        } catch (TwitterException | IllegalStateException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        recargarTweets();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jPanelComponenteTweet = new javax.swing.JPanel();
        jButtonPublicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaMaxLenght1 = new twitter.interfaz.TextAreaMaxLenght();
        jPanelCabecera = new javax.swing.JPanel();
        jButtonInicio = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar1 = new javax.swing.JButton();
        jPanelTT = new javax.swing.JPanel();
        jLabelTT = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTTGlobal = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPaneTT = new javax.swing.JScrollPane();
        jListTTEsp = new javax.swing.JList<>();
        jPanelInfo = new javax.swing.JPanel();
        jPanelInfoPerfil = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNickName = new javax.swing.JLabel();
        jLabelTweets = new javax.swing.JLabel();
        jLabelSiguiendo = new javax.swing.JLabel();
        jLabelSeguidores = new javax.swing.JLabel();
        jButtonlCantidadSiguiendo = new javax.swing.JButton();
        jButtonlCantidadSeguidores = new javax.swing.JButton();
        jButtonTweets = new javax.swing.JButton();
        jPanelInfoBackground = new javax.swing.JPanel();
        jLabelInfoBackground = new javax.swing.JLabel();
        jPanelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1023, 581));
        setResizable(false);

        jPanelBase.setBackground(new java.awt.Color(231, 229, 229));
        jPanelBase.setMinimumSize(new java.awt.Dimension(1023, 581));
        jPanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelComponenteTweet.setBackground(new java.awt.Color(207, 237, 237));
        jPanelComponenteTweet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonPublicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonPublicar.setText("Publicar");
        jButtonPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPublicarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("¿ Que esta pasando?");

        textAreaMaxLenght1.setColumns(20);
        textAreaMaxLenght1.setRows(5);
        jScrollPane2.setViewportView(textAreaMaxLenght1);

        javax.swing.GroupLayout jPanelComponenteTweetLayout = new javax.swing.GroupLayout(jPanelComponenteTweet);
        jPanelComponenteTweet.setLayout(jPanelComponenteTweetLayout);
        jPanelComponenteTweetLayout.setHorizontalGroup(
            jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComponenteTweetLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComponenteTweetLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                        .addGap(125, 125, 125))
                    .addGroup(jPanelComponenteTweetLayout.createSequentialGroup()
                        .addGroup(jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelComponenteTweetLayout.setVerticalGroup(
            jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComponenteTweetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBase.add(jPanelComponenteTweet, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 50, 730, 170));

        jPanelCabecera.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCabecera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonInicio.setText("Inicio");
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar perfil");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonBuscar1.setText("Buscar tweets");
        jButtonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCabeceraLayout = new javax.swing.GroupLayout(jPanelCabecera);
        jPanelCabecera.setLayout(jPanelCabeceraLayout);
        jPanelCabeceraLayout.setHorizontalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCabeceraLayout.setVerticalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldBuscar))
                    .addComponent(jButtonInicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBase.add(jPanelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1020, 60));

        jPanelTT.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTT.setText("Trending Topics");

        jListTTGlobal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jListTTGlobal);

        jTabbedPane1.addTab("Global", jScrollPane1);

        jListTTEsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPaneTT.setViewportView(jListTTEsp);

        jScrollPane3.setViewportView(jScrollPaneTT);

        jTabbedPane1.addTab("España", jScrollPane3);

        javax.swing.GroupLayout jPanelTTLayout = new javax.swing.GroupLayout(jPanelTT);
        jPanelTT.setLayout(jPanelTTLayout);
        jPanelTTLayout.setHorizontalGroup(
            jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabelTT)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(jPanelTTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTTLayout.setVerticalGroup(
            jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTT)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Trending Topics Global");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        jPanelBase.add(jPanelTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, 550));

        jPanelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInfoPerfil.setBackground(new java.awt.Color(255, 255, 255));

        jLabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUsuario.setText("@Usuario");

        jLabelNickName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNickName.setText("NickName");

        jLabelTweets.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTweets.setText("Tweets");

        jLabelSiguiendo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSiguiendo.setText("Siguiendo");

        jLabelSeguidores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSeguidores.setText("Seguidores");

        jButtonlCantidadSiguiendo.setText("0");
        jButtonlCantidadSiguiendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlCantidadSiguiendoActionPerformed(evt);
            }
        });

        jButtonlCantidadSeguidores.setText("0");
        jButtonlCantidadSeguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlCantidadSeguidoresActionPerformed(evt);
            }
        });

        jButtonTweets.setText("0");

        javax.swing.GroupLayout jPanelInfoPerfilLayout = new javax.swing.GroupLayout(jPanelInfoPerfil);
        jPanelInfoPerfil.setLayout(jPanelInfoPerfilLayout);
        jPanelInfoPerfilLayout.setHorizontalGroup(
            jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNickName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInfoPerfilLayout.createSequentialGroup()
                        .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTweets)
                            .addComponent(jButtonTweets, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSiguiendo)
                            .addComponent(jButtonlCantidadSiguiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelSeguidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonlCantidadSeguidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelInfoPerfilLayout.setVerticalGroup(
            jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTweets)
                    .addComponent(jLabelSiguiendo)
                    .addComponent(jLabelSeguidores))
                .addGap(2, 2, 2)
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonlCantidadSiguiendo)
                    .addComponent(jButtonlCantidadSeguidores)
                    .addComponent(jButtonTweets))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelInfo.add(jPanelInfoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 160));

        javax.swing.GroupLayout jPanelInfoBackgroundLayout = new javax.swing.GroupLayout(jPanelInfoBackground);
        jPanelInfoBackground.setLayout(jPanelInfoBackgroundLayout);
        jPanelInfoBackgroundLayout.setHorizontalGroup(
            jPanelInfoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInfoBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jPanelInfoBackgroundLayout.setVerticalGroup(
            jPanelInfoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInfoBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanelInfo.add(jPanelInfoBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));

        jPanelBase.add(jPanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 170));

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanelBase.add(jPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 730, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPublicarActionPerformed
        GestionTwitter.sendTwitt(twitterConnection, textAreaMaxLenght1.getText());
        textAreaMaxLenght1.setText("");
    }//GEN-LAST:event_jButtonPublicarActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        recargarTweets();
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonlCantidadSiguiendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlCantidadSiguiendoActionPerformed
        DialogoSeguidores dialogoSeguidores = new DialogoSeguidores(null, rootPaneCheckingEnabled, GestionTwitter.seguidos(twitterConnection));
        dialogoSeguidores.setVisible(true);
    }//GEN-LAST:event_jButtonlCantidadSiguiendoActionPerformed

    private void jButtonlCantidadSeguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlCantidadSeguidoresActionPerformed
        DialogoSeguidores dialogoSeguidores = new DialogoSeguidores(null, rootPaneCheckingEnabled, GestionTwitter.seguidores(twitterConnection));
        dialogoSeguidores.setVisible(true);
    }//GEN-LAST:event_jButtonlCantidadSeguidoresActionPerformed

    private void jButtonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscar1ActionPerformed
        List<Status> tweets = GestionTwitter.buscarTopic(twitterConnection, jTextFieldBuscar.getText());
        for (Status tweet : tweets) {
            System.out.println(tweet.getText());
        }
        DialogTweets dialogTweets = new DialogTweets(null, rootPaneCheckingEnabled, tweets, twitterConnection);
        dialogTweets.setVisible(true);
    }//GEN-LAST:event_jButtonBuscar1ActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        List<Status> tweets = GestionTwitter.buscarUsuario(twitterConnection, jTextFieldBuscar.getText());
        for (Status tweet : tweets) {
            System.out.println(tweet.getText());
        }
        DialogTweets dialogTweets = new DialogTweets(null, rootPaneCheckingEnabled, tweets, twitterConnection);
        dialogTweets.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscar1;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonPublicar;
    private javax.swing.JButton jButtonTweets;
    private javax.swing.JButton jButtonlCantidadSeguidores;
    private javax.swing.JButton jButtonlCantidadSiguiendo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInfoBackground;
    private javax.swing.JLabel jLabelNickName;
    private javax.swing.JLabel jLabelSeguidores;
    private javax.swing.JLabel jLabelSiguiendo;
    private javax.swing.JLabel jLabelTT;
    private javax.swing.JLabel jLabelTweets;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JList<String> jListTTEsp;
    private javax.swing.JList<String> jListTTGlobal;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelComponenteTweet;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInfoBackground;
    private javax.swing.JPanel jPanelInfoPerfil;
    private javax.swing.JPanel jPanelTT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneTT;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldBuscar;
    private twitter.interfaz.TextAreaMaxLenght textAreaMaxLenght1;
    // End of variables declaration//GEN-END:variables

    private void recargarTweets() {
        GridBagLayout layout = new GridBagLayout();
        JPanel panelTweets = new JPanel();
        panelTweets.setLayout(layout);
        jPanelContenedor.setLayout(new BorderLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        List<Status> homeTimeline = GestionTwitter.getHomeTimeline(twitterConnection);
        int contador = 0;
        for (Status status : homeTimeline) {
            TweetComponent tweetComponent = new TweetComponent(status, twitterConnection);
            gbc.gridx = 0;
            gbc.gridy = contador;
            panelTweets.add(tweetComponent, gbc);
            contador++;
        }
        jPanelContenedor.add(new JScrollPane(panelTweets, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED), BorderLayout.CENTER);
    }
}
