/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter.interfaz;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import logica.GestionTwitter;
import twitter4j.Status;
import twitter4j.Twitter;
import twitter4j.TwitterException;

/**
 *
 * @author migue
 */
public class PantallaPrincipal extends javax.swing.JDialog {
    
    Twitter twitterConnection;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal(java.awt.Frame parent, boolean modal, Twitter twitterConnection) {
        super(parent, modal);
        this.twitterConnection = twitterConnection;
        initComponents();
        setLocationRelativeTo(parent);
        try {
            jLabelUsuario.setText("@"+twitterConnection.getScreenName());
            jLabelNickName.setText(twitterConnection.getUserTimeline().get(0).getUser().getName());
        } catch (TwitterException | IllegalStateException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        recargarTweets();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jPanelComponenteTweet = new javax.swing.JPanel();
        jButtonPublicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaMaxLenght1 = new twitter.interfaz.TextAreaMaxLenght();
        jPanelCabecera = new javax.swing.JPanel();
        jButtonInicio = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonPerfil = new javax.swing.JButton();
        jPanelTT = new javax.swing.JPanel();
        jLabelTT = new javax.swing.JLabel();
        jScrollPaneTT = new javax.swing.JScrollPane();
        jListTT = new javax.swing.JList<>();
        jPanelInfo = new javax.swing.JPanel();
        jPanelInfoPerfil = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNickName = new javax.swing.JLabel();
        jLabelTweets = new javax.swing.JLabel();
        jLabelSiguiendo = new javax.swing.JLabel();
        jLabelSeguidores = new javax.swing.JLabel();
        jLabelCantidadTweets = new javax.swing.JLabel();
        jLabelCantidadSiguiendo = new javax.swing.JLabel();
        jLabelCantidadSeguidores = new javax.swing.JLabel();
        jLabelAvatarInfo = new javax.swing.JLabel();
        jPanelInfoBackground = new javax.swing.JPanel();
        jLabelInfoBackground = new javax.swing.JLabel();
        jPanelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1023, 581));
        setResizable(false);

        jPanelBase.setBackground(new java.awt.Color(231, 229, 229));
        jPanelBase.setMinimumSize(new java.awt.Dimension(1023, 581));
        jPanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelComponenteTweet.setBackground(new java.awt.Color(207, 237, 237));
        jPanelComponenteTweet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonPublicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonPublicar.setText("Publicar");
        jButtonPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPublicarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("¿ Que esta pasando?");

        textAreaMaxLenght1.setColumns(20);
        textAreaMaxLenght1.setRows(5);
        jScrollPane2.setViewportView(textAreaMaxLenght1);

        javax.swing.GroupLayout jPanelComponenteTweetLayout = new javax.swing.GroupLayout(jPanelComponenteTweet);
        jPanelComponenteTweet.setLayout(jPanelComponenteTweetLayout);
        jPanelComponenteTweetLayout.setHorizontalGroup(
            jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComponenteTweetLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComponenteTweetLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                        .addGap(125, 125, 125))
                    .addGroup(jPanelComponenteTweetLayout.createSequentialGroup()
                        .addGroup(jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelComponenteTweetLayout.setVerticalGroup(
            jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComponenteTweetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBase.add(jPanelComponenteTweet, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 50, 730, 170));

        jPanelCabecera.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCabecera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonInicio.setText("Inicio");
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");

        jButtonPerfil.setText("Perfil");
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCabeceraLayout = new javax.swing.GroupLayout(jPanelCabecera);
        jPanelCabecera.setLayout(jPanelCabeceraLayout);
        jPanelCabeceraLayout.setHorizontalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInicio)
                .addGap(18, 18, 18)
                .addComponent(jButtonPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addContainerGap())
        );
        jPanelCabeceraLayout.setVerticalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldBuscar)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jButtonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBase.add(jPanelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1020, 60));

        jPanelTT.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTT.setText("Trending Topics");

        jListTT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jListTT.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneTT.setViewportView(jListTT);

        javax.swing.GroupLayout jPanelTTLayout = new javax.swing.GroupLayout(jPanelTT);
        jPanelTT.setLayout(jPanelTTLayout);
        jPanelTTLayout.setHorizontalGroup(
            jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTT, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTT))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanelTTLayout.setVerticalGroup(
            jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTT, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBase.add(jPanelTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, 550));

        jPanelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInfoPerfil.setBackground(new java.awt.Color(255, 255, 255));

        jLabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUsuario.setText("@Usuario");

        jLabelNickName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNickName.setText("NickName");

        jLabelTweets.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTweets.setText("Tweets");

        jLabelSiguiendo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSiguiendo.setText("Siguiendo");

        jLabelSeguidores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSeguidores.setText("Seguidores");

        jLabelCantidadTweets.setText("0");

        jLabelCantidadSiguiendo.setText("0");

        jLabelCantidadSeguidores.setText("0");

        jLabelAvatarInfo.setText("Avatar");

        javax.swing.GroupLayout jPanelInfoPerfilLayout = new javax.swing.GroupLayout(jPanelInfoPerfil);
        jPanelInfoPerfil.setLayout(jPanelInfoPerfilLayout);
        jPanelInfoPerfilLayout.setHorizontalGroup(
            jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addComponent(jLabelTweets)
                        .addGap(45, 45, 45)
                        .addComponent(jLabelSiguiendo)
                        .addGap(49, 49, 49)
                        .addComponent(jLabelSeguidores))
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCantidadTweets, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabelCantidadSiguiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabelCantidadSeguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addComponent(jLabelAvatarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNickName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelInfoPerfilLayout.setVerticalGroup(
            jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAvatarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jLabelUsuario)
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTweets)
                    .addComponent(jLabelSiguiendo)
                    .addComponent(jLabelSeguidores))
                .addGap(6, 6, 6)
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCantidadTweets)
                    .addComponent(jLabelCantidadSiguiendo)
                    .addComponent(jLabelCantidadSeguidores))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelInfo.add(jPanelInfoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 160));

        javax.swing.GroupLayout jPanelInfoBackgroundLayout = new javax.swing.GroupLayout(jPanelInfoBackground);
        jPanelInfoBackground.setLayout(jPanelInfoBackgroundLayout);
        jPanelInfoBackgroundLayout.setHorizontalGroup(
            jPanelInfoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInfoBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jPanelInfoBackgroundLayout.setVerticalGroup(
            jPanelInfoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInfoBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanelInfo.add(jPanelInfoBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));

        jPanelBase.add(jPanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 170));

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanelBase.add(jPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 730, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPublicarActionPerformed
        GestionTwitter.sendTwitt(twitterConnection,textAreaMaxLenght1.getText() );
        textAreaMaxLenght1.setText("");
    }//GEN-LAST:event_jButtonPublicarActionPerformed

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        recargarTweets();
    }//GEN-LAST:event_jButtonInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JButton jButtonPublicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAvatarInfo;
    private javax.swing.JLabel jLabelCantidadSeguidores;
    private javax.swing.JLabel jLabelCantidadSiguiendo;
    private javax.swing.JLabel jLabelCantidadTweets;
    private javax.swing.JLabel jLabelInfoBackground;
    private javax.swing.JLabel jLabelNickName;
    private javax.swing.JLabel jLabelSeguidores;
    private javax.swing.JLabel jLabelSiguiendo;
    private javax.swing.JLabel jLabelTT;
    private javax.swing.JLabel jLabelTweets;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JList<String> jListTT;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelComponenteTweet;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInfoBackground;
    private javax.swing.JPanel jPanelInfoPerfil;
    private javax.swing.JPanel jPanelTT;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneTT;
    private javax.swing.JTextField jTextFieldBuscar;
    private twitter.interfaz.TextAreaMaxLenght textAreaMaxLenght1;
    // End of variables declaration//GEN-END:variables

    private void recargarTweets() {
        GridBagLayout layout = new GridBagLayout();
        JPanel panelTweets = new JPanel();
        panelTweets.setLayout(layout);
        jPanelContenedor.setLayout(new BorderLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        List<Status> homeTimeline = GestionTwitter.getHomeTimeline(twitterConnection);
        int contador = 0;
        for (Status status : homeTimeline) {
            TweetComponent tweetComponent = new TweetComponent(status);
            gbc.gridx = 0;
            gbc.gridy = contador;
            panelTweets.add(tweetComponent, gbc);
            contador++;
        }
        jPanelContenedor.add(new JScrollPane(panelTweets, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED), BorderLayout.CENTER);
    }
}
