/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter.interfaz;

import java.io.Serializable;
import javax.swing.Icon;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import logica.GestionTwitter;
import mdlaf.utils.MaterialColors;
import twitter4j.Status;
import twitter4j.Twitter;

/**
 *
 * @author Jordy
 */
public class TweetComponent extends javax.swing.JPanel implements Serializable {

    Twitter twitterConnection;
    Status status;

    TweetComponent(Status status, Twitter twitterConnection) {
        initComponents();
        this.twitterConnection = twitterConnection;
        this.status = status;
       /* UIManager.put("Button.background", MaterialColors.WHITE);
        UIManager.put("Button.foreground", MaterialColors.BLUE_600);
        jButtonUsuario.setBorder(new LineBorder(MaterialColors.BLUE_600));*/
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.append(status.getText());
        jButtonUsuario.setText(status.getUser().getName());
        jLabelFecha.setText("@" + status.getUser().getScreenName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonResponder = new javax.swing.JButton();
        jButtonRetweet = new javax.swing.JButton();
        jButtonLike = new javax.swing.JButton();
        jButtonMensaje = new javax.swing.JButton();
        jButtonUsuario = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jButtonResponder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitter/img/arrow_post_share_tweet_icon_32.png"))); // NOI18N
        jButtonResponder.setBorderPainted(false);
        jButtonResponder.setMaximumSize(new java.awt.Dimension(24, 24));
        jButtonResponder.setMinimumSize(new java.awt.Dimension(24, 24));
        jButtonResponder.setPreferredSize(new java.awt.Dimension(24, 24));

        jButtonRetweet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitter/img/arrows_repeat_retweet_share_icon_32.png"))); // NOI18N
        jButtonRetweet.setBorderPainted(false);
        jButtonRetweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetweetActionPerformed(evt);
            }
        });

        jButtonLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitter/img/heart_like_love_twitter_icon_32.png"))); // NOI18N
        jButtonLike.setBorderPainted(false);

        jButtonMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitter/img/chat_comments_inbox_message_icon_32.png"))); // NOI18N
        jButtonMensaje.setBorderPainted(false);
        jButtonMensaje.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jButtonMensajeComponentRemoved(evt);
            }
        });

        jButtonUsuario.setText("usuario");

        jLabelFecha.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabelFecha.setText("fecha");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonResponder, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonRetweet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonLike, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(237, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUsuario)
                    .addComponent(jLabelFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonResponder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRetweet, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLike, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMensajeComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jButtonMensajeComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMensajeComponentRemoved

    private void jButtonRetweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetweetActionPerformed
        GestionTwitter.retwitear(twitterConnection, status.getId());
    }//GEN-LAST:event_jButtonRetweetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLike;
    private javax.swing.JButton jButtonMensaje;
    private javax.swing.JButton jButtonResponder;
    private javax.swing.JButton jButtonRetweet;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
