package interfaz;

public class PantallaGeneral extends javax.swing.JDialog {

    public PantallaGeneral(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jPanelComponenteTweet = new javax.swing.JPanel();
        jPanelCabecera = new javax.swing.JPanel();
        jButtonInicio = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonPerfil = new javax.swing.JButton();
        jPanelTT = new javax.swing.JPanel();
        jLabelTT = new javax.swing.JLabel();
        jScrollPaneTT = new javax.swing.JScrollPane();
        jListTT = new javax.swing.JList<>();
        jPanelTimeline = new javax.swing.JPanel();
        jPanelInfo = new javax.swing.JPanel();
        jPanelInfoPerfil = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNickName = new javax.swing.JLabel();
        jLabelTweets = new javax.swing.JLabel();
        jLabelSiguiendo = new javax.swing.JLabel();
        jLabelSeguidores = new javax.swing.JLabel();
        jLabelCantidadTweets = new javax.swing.JLabel();
        jLabelCantidadSiguiendo = new javax.swing.JLabel();
        jLabelCantidadSeguidores = new javax.swing.JLabel();
        jLabelAvatarInfo = new javax.swing.JLabel();
        jPanelInfoBackground = new javax.swing.JPanel();
        jLabelInfoBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelBase.setBackground(new java.awt.Color(231, 229, 229));
        jPanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelComponenteTweet.setBackground(new java.awt.Color(207, 237, 237));
        jPanelComponenteTweet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelComponenteTweetLayout = new javax.swing.GroupLayout(jPanelComponenteTweet);
        jPanelComponenteTweet.setLayout(jPanelComponenteTweetLayout);
        jPanelComponenteTweetLayout.setHorizontalGroup(
            jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        jPanelComponenteTweetLayout.setVerticalGroup(
            jPanelComponenteTweetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        jPanelBase.add(jPanelComponenteTweet, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 50, 650, 170));

        jPanelCabecera.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCabecera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonInicio.setText("Inicio");

        jButtonBuscar.setText("Buscar");

        jButtonPerfil.setText("Perfil");

        javax.swing.GroupLayout jPanelCabeceraLayout = new javax.swing.GroupLayout(jPanelCabecera);
        jPanelCabecera.setLayout(jPanelCabeceraLayout);
        jPanelCabeceraLayout.setHorizontalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButtonInicio)
                .addGap(38, 38, 38)
                .addComponent(jButtonPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 440, Short.MAX_VALUE)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addContainerGap())
        );
        jPanelCabeceraLayout.setVerticalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInicio)
                    .addComponent(jButtonBuscar)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPerfil))
                .addGap(158, 158, 158))
        );

        jPanelBase.add(jPanelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 50));

        jPanelTT.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTT.setText("Trending Topics");

        jListTT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jListTT.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneTT.setViewportView(jListTT);

        javax.swing.GroupLayout jPanelTTLayout = new javax.swing.GroupLayout(jPanelTT);
        jPanelTT.setLayout(jPanelTTLayout);
        jPanelTTLayout.setHorizontalGroup(
            jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTT, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTT))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanelTTLayout.setVerticalGroup(
            jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTT, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBase.add(jPanelTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, 260));

        jPanelTimeline.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTimelineLayout = new javax.swing.GroupLayout(jPanelTimeline);
        jPanelTimeline.setLayout(jPanelTimelineLayout);
        jPanelTimelineLayout.setHorizontalGroup(
            jPanelTimelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanelTimelineLayout.setVerticalGroup(
            jPanelTimelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanelBase.add(jPanelTimeline, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 650, 600));

        jPanelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInfoPerfil.setBackground(new java.awt.Color(255, 255, 255));

        jLabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUsuario.setText("@Usuario");

        jLabelNickName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNickName.setText("NickName");

        jLabelTweets.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTweets.setText("Tweets");

        jLabelSiguiendo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSiguiendo.setText("Siguiendo");

        jLabelSeguidores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSeguidores.setText("Seguidores");

        jLabelCantidadTweets.setText("0");

        jLabelCantidadSiguiendo.setText("0");

        jLabelCantidadSeguidores.setText("0");

        jLabelAvatarInfo.setText("Avatar");

        javax.swing.GroupLayout jPanelInfoPerfilLayout = new javax.swing.GroupLayout(jPanelInfoPerfil);
        jPanelInfoPerfil.setLayout(jPanelInfoPerfilLayout);
        jPanelInfoPerfilLayout.setHorizontalGroup(
            jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelAvatarInfo)
                        .addGap(45, 45, 45)
                        .addComponent(jLabelNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addComponent(jLabelTweets)
                        .addGap(45, 45, 45)
                        .addComponent(jLabelSiguiendo)
                        .addGap(49, 49, 49)
                        .addComponent(jLabelSeguidores))
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCantidadTweets, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabelCantidadSiguiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabelCantidadSeguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelInfoPerfilLayout.setVerticalGroup(
            jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoPerfilLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoPerfilLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelAvatarInfo))
                    .addComponent(jLabelNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabelUsuario)
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTweets)
                    .addComponent(jLabelSiguiendo)
                    .addComponent(jLabelSeguidores))
                .addGap(6, 6, 6)
                .addGroup(jPanelInfoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCantidadTweets)
                    .addComponent(jLabelCantidadSiguiendo)
                    .addComponent(jLabelCantidadSeguidores)))
        );

        jPanelInfo.add(jPanelInfoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 100));

        javax.swing.GroupLayout jPanelInfoBackgroundLayout = new javax.swing.GroupLayout(jPanelInfoBackground);
        jPanelInfoBackground.setLayout(jPanelInfoBackgroundLayout);
        jPanelInfoBackgroundLayout.setHorizontalGroup(
            jPanelInfoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInfoBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jPanelInfoBackgroundLayout.setVerticalGroup(
            jPanelInfoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInfoBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanelInfo.add(jPanelInfoBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));

        jPanelBase.add(jPanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaGeneral dialog = new PantallaGeneral(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JLabel jLabelAvatarInfo;
    private javax.swing.JLabel jLabelCantidadSeguidores;
    private javax.swing.JLabel jLabelCantidadSiguiendo;
    private javax.swing.JLabel jLabelCantidadTweets;
    private javax.swing.JLabel jLabelInfoBackground;
    private javax.swing.JLabel jLabelNickName;
    private javax.swing.JLabel jLabelSeguidores;
    private javax.swing.JLabel jLabelSiguiendo;
    private javax.swing.JLabel jLabelTT;
    private javax.swing.JLabel jLabelTweets;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JList<String> jListTT;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelComponenteTweet;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInfoBackground;
    private javax.swing.JPanel jPanelInfoPerfil;
    private javax.swing.JPanel jPanelTT;
    private javax.swing.JPanel jPanelTimeline;
    private javax.swing.JScrollPane jScrollPaneTT;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
