/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timeline;

import java.io.Serializable;

/**
 *
 * @author Jordy
 */
public class Timeline extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form Timeline
     */
    public Timeline() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonResponder = new javax.swing.JButton();
        jButtonRetweet = new javax.swing.JButton();
        jButtonLike = new javax.swing.JButton();
        jButtonMensaje = new javax.swing.JButton();
        jLabelAvatar = new javax.swing.JLabel();
        jButtonUsuario = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jLabelIDUsuario = new javax.swing.JLabel();
        jTextFieldTweet = new javax.swing.JTextField();

        jButtonResponder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-burbuja-de-diálogo-24.png"))); // NOI18N
        jButtonResponder.setBorderPainted(false);
        jButtonResponder.setMaximumSize(new java.awt.Dimension(24, 24));
        jButtonResponder.setMinimumSize(new java.awt.Dimension(24, 24));
        jButtonResponder.setPreferredSize(new java.awt.Dimension(24, 24));

        jButtonRetweet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-retweet-24.png"))); // NOI18N
        jButtonRetweet.setBorderPainted(false);

        jButtonLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-corazones-24.png"))); // NOI18N
        jButtonLike.setBorderPainted(false);

        jButtonMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-mensaje-24.png"))); // NOI18N
        jButtonMensaje.setBorderPainted(false);
        jButtonMensaje.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jButtonMensajeComponentRemoved(evt);
            }
        });

        jLabelAvatar.setText("Avatar");
        jLabelAvatar.setMaximumSize(new java.awt.Dimension(48, 48));
        jLabelAvatar.setMinimumSize(new java.awt.Dimension(48, 48));
        jLabelAvatar.setPreferredSize(new java.awt.Dimension(48, 48));

        jButtonUsuario.setText("usuario");

        jLabelFecha.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabelFecha.setText("fecha");

        jLabelIDUsuario.setText("@usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonResponder, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonRetweet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonLike, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTweet)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelIDUsuario)
                                .addGap(58, 58, 58)
                                .addComponent(jLabelFecha)
                                .addGap(0, 70, Short.MAX_VALUE)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonUsuario)
                            .addComponent(jLabelIDUsuario)
                            .addComponent(jLabelFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(217, 217, 217)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonResponder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRetweet, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLike, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMensajeComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jButtonMensajeComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMensajeComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLike;
    private javax.swing.JButton jButtonMensaje;
    private javax.swing.JButton jButtonResponder;
    private javax.swing.JButton jButtonRetweet;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JLabel jLabelAvatar;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelIDUsuario;
    private javax.swing.JTextField jTextFieldTweet;
    // End of variables declaration//GEN-END:variables
}
